### ISSUE TITLE
No website shown

### ISSUE THREAD

**Issue by jcnt-creations** [aichner/company-homepage#17]
**Describe the bug**
The website doesn't get loaded and the "div id=root" is empty

**To Reproduce**
1. load the page

**Expected behavior**
Get the website

**Screenshots**
![image](https://user-images.githubusercontent.com/52113020/81701790-c32a6080-946a-11ea-88f2-65bebb6d53cf.png)  
![image](https://user-images.githubusercontent.com/52113020/81701869-db01e480-946a-11ea-968c-06274a374340.png)

**Desktop (please complete the following information):**
  - OS: Windoof
  - Browser: Chrome
  - Version: 81.0

**Smartphone (please complete the following information):**  
worked
  - Device: Huawei
  - OS: Android 9
  - Browser: Chrome
  - Version: 81

**Additional context**
Why so many infos about me??

**Comment by Aichnerc** [comment]
The issue has been identified as a user-related issue, caused by either anti-virus software, browser extensions and/or bad internet connection.
